services:
  - type: web
    name: student-hustle-hub-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 947039282232-c3t04h5tuehfqi5h8psjqa12rtd0igt6.apps.googleusercontent.com
      - key: ADMIN_EMAILS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
